### ISSUE TITLE
Функциональные требования.

### ISSUE THREAD

**Issue by RS00** [NikitaKozelko/ToDo-List#3]
Добрый вечер. У Вас в функциональных требованиях сказано, что можно будет создавать задачи без указания крайнего срока выполнения. Проанализировав все описанное, можно сделать вывод, что единственным способом увидеть такие задачи можно будет во вкладке "All". При этом сказано, что в этой вкладке задачи будут сортироваться по дате создания. Если у меня будет очень много задач => старые задачи без даты запросто могут оказаться где-то снизу, и придется каждый раз пролистывать список, чтобы их увидеть. К тому же, в данном случае я могу просто забыть об их существовании. Может стоит добавить специальную вкладку для таких задач? Или изменить логику отображения задач для этой вкладки?

**Comment by NikitaKozelko** [comment]
Добрый вечер. Спасибо за указанный недочет. Соглашусь, что будет логично добавить специальную вкладку с забытыми задачами.
